# Generated by Django 4.0.1 on 2022-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_material_description_publication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
