# Generated by Django 4.0.1 on 2022-01-29 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_material_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
