# Generated by Django 4.0.1 on 2022-01-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='room',
        ),
    ]
