# Generated by Django 4.0.1 on 2022-01-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_remove_publication_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Room.room'),
            preserve_default=False,
        ),
    ]
